"""Export the configuration and diamond models as JSON Schemas.

Written to ``config/schemas/``. They serve three purposes:

- editor validation of the YAML files (``yaml-language-server`` header),
- TypeScript type generation in ``web/`` (``npm run gen:types``),
- a CI check that committed schemas match the code (``bluebird schemas --check``).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Literal

from pydantic import BaseModel

from .config import (
    FiltersFile,
    KpisFile,
    LayoutFile,
    MassifsFile,
    PagesFile,
    RewindsFile,
    SourcesFile,
    StationsFile,
    TilesFile,
)
from .diamond.models import DiamondManifest, DiamondMassifDaily, DiamondRewind

Mode = Literal["validation", "serialization"]

# file stem -> (model, mode). Config files are read (validation mode: fields with
# defaults are optional); diamond files are written (serialization: all present).
SCHEMAS: dict[str, tuple[type[BaseModel], Mode]] = {
    "massifs": (MassifsFile, "validation"),
    "stations": (StationsFile, "validation"),
    "kpis": (KpisFile, "validation"),
    "filters": (FiltersFile, "validation"),
    "tiles": (TilesFile, "validation"),
    "layout": (LayoutFile, "validation"),
    "sources": (SourcesFile, "validation"),
    "pages": (PagesFile, "validation"),
    "rewinds": (RewindsFile, "validation"),
    "diamond-massif-daily": (DiamondMassifDaily, "serialization"),
    "diamond-manifest": (DiamondManifest, "serialization"),
    "diamond-rewind": (DiamondRewind, "serialization"),
}


def render(name: str) -> str:
    model, mode = SCHEMAS[name]
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": "Generated by `bluebird schemas`. Do not edit by hand.",
        **model.model_json_schema(mode=mode),
    }
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def write_schemas(directory: Path) -> list[Path]:
    directory.mkdir(parents=True, exist_ok=True)
    paths = []
    for name in SCHEMAS:
        path = directory / f"{name}.schema.json"
        path.write_text(render(name), encoding="utf-8")
        paths.append(path)
    return paths


def stale_schemas(directory: Path) -> list[str]:
    """Names of schemas whose committed file differs from the code."""
    stale = []
    for name in SCHEMAS:
        path = directory / f"{name}.schema.json"
        if not path.is_file() or path.read_text(encoding="utf-8") != render(name):
            stale.append(name)
    return stale
